Repository linewalks/MDwalks-UI, pull requests merged in 2019-11, with the labels that each got.

#235 트리맵 차트 및 테스트 추가
  index.mdx
  src/components/__tests__/TreeMap.test.js
  src/components/charts/TreeMap.js
  src/docz/Charts.mdx
  src/index.js
Labels: Component, DONE

#239 Create SelectBox
  doczrc.js
  package.json
  src/assets/svg/icn_select_open_sm.svg
  src/assets/svg/icn_select_open_xs.svg
  src/components/form/SelectBox.js
  src/docz/Modal.mdx
  src/docz/custom.css
  src/docz/form.mdx
  src/index.js
  yarn.lock
Labels: Component

#237 create guild
  README.md
Labels: DONE, docs

#241 Feature/code.cleanup
  .babelrc
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  README.md
  gatsby-node.js
  package-lock.json
  package.json
  src/components/__tests__/Histogram.test.js
  src/components/__tests__/Modal.test.js
  src/components/button/Button.js
  src/components/button/utility.test.js
  src/components/card/SelectedCard.js
  src/components/card/SummaryCard.js
  src/components/charts/BarGauge.js
  src/components/charts/Histogram.js
  src/components/charts/LineChart.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/RadarChart.js
  src/components/charts/RadiusGauge.js
  src/components/charts/SankeyChart.js
  src/components/charts/Timeline.js
  src/components/form/SelectBox.js
  src/components/layout/Footer.js
  src/components/layout/Heading.js
  src/components/layout/Navbar.js
  src/components/list/CheckList.js
  src/components/list/CheckList.test.js
  src/components/modal/Modal.js
  src/components/paper/Heatmap.js
  src/components/paper/Sequence.js
  src/components/table/Descriptions.js
  src/components/table/TBody.js
  src/components/table/TFoot.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/docz/Button.mdx
  src/docz/Card.mdx
  src/docz/Charts.mdx
  src/docz/Layout.mdx
  src/docz/List.mdx
  src/docz/Modal.mdx
  src/docz/Paper.mdx
  src/docz/Table.mdx
  src/docz/form.mdx
  src/helper/chartUtility.test.js
  src/index.js
  stories/BarGauge.js
  stories/LineMergeTimeline.js
  stories/RadiusGauge.js
  stories/SankeyChart.js
  stories/SelectedCard.js
  stories/SummaryCard.js
  stories/Table.js
  stories/Timeline.js
  yarn.lock
Labels: Build, Component, DONE, docs

#245 Craete Tab Component
  src/assets/styles/font.js
  src/components/__tests__/Tabs.test.js
  src/components/button/utility.js
  src/components/button/utility.test.js
  src/components/layout/Tabs.js
  src/docz/Layout.mdx
  src/index.js
Labels: CSS, Component, docs

#247 Create xlg Button
  src/components/button/Button.js
  src/docz/Button.mdx
Labels: Component

#249 fixed: set width, height on Image Component
  src/components/__tests__/Image.test.js
  src/components/layout/Image.js
Labels: Component, bug

#246 차트 에러메세지 util 함수로 만들고, 모든차트에서 적용.
  src/components/__tests__/LineChart.test.js
  src/components/__tests__/RadarChart.test.js
  src/components/__tests__/TreeMap.test.js
  src/components/charts/Histogram.js
  src/components/charts/LineChart.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/RadarChart.js
  src/components/charts/Timeline.js
  src/components/charts/TreeMap.js
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Component

#252 Update README.md
  README.md
Labels: docs

#254 [비교페이지] MACE 시점으로 변경되어도 툴팁에 I.I.T risk score로 고정됨
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.js
  src/docz/Charts.mdx
Labels: Component, bug

#256 Feature/issue.250
  doczrc.js
  src/assets/svg/toast/icn_message_complete.svg
  src/assets/svg/toast/icn_message_error.svg
  src/assets/svg/toast/icn_toast_complete_close_default.svg
  src/assets/svg/toast/icn_toast_error_close_default.svg
  src/components/__tests__/ToastList.test.js
  src/components/toast/Toast.js
  src/components/toast/ToastCtr.js
  src/components/toast/ToastList.js
  src/docz/Toast.mdx
  src/index.js
Labels: Component

#261 apply Selecbox to Heatmap
  src/components/paper/Heatmap.js
  src/docz/Charts.mdx
Labels: Component, docs

#265 support rowSpan to Table
  src/components/__tests__/Table.test.js
  src/components/table/TBody.js
  src/docz/Table.mdx
  yarn.lock
Labels: Component

#262 Treemap docz build 시 에러
  src/components/charts/TreeMap.js
Labels: Component, bug

#253 TimeToEvent 이동 및 테스트코드 추가
  index.mdx
  src/components/__tests__/TimeToEvent.test.js
  src/components/charts/TimeToEvent.js
  src/components/charts/TimeToEvent.module.css
  src/docz/Charts.mdx
  src/index.js
Labels: Component, test

#267 docs: append Commit Guide
  README.md
Labels: docs

#270 fix(README): table markdown
  README.md
Labels: docs

#273 Paging 컴포넌트와 테스트를 UI레포로 이동
  index.mdx
  package.json
  src/assets/svg/pagination/btn_next.svg
  src/assets/svg/pagination/btn_pre.svg
  src/components/__tests__/Pagination.test.js
  src/components/pagination/Pagination.js
  src/docz/Pagenation.mdx
  src/index.js
  yarn.lock
Labels: Component

#274 ESLint 추가
  .eslintignore
  .eslintrc.js
  package.json
  yarn.lock
Labels: Component

#275 feat(travis): modify travis.yml
  .travis.yml
Labels: CI

#277 feat(changelog): update
  CHANGELOG.md
Labels: Build

#282 imporvement(THead): mapping subHeaders
  src/components/__tests__/Table.test.js
  src/components/table/TBody.js
  src/components/table/THead.js
  src/components/table/Table.js
Labels: Component

#285 Feature/issue.281
  .eslintrc.js
  package.json
  src/components/__tests__/Tabs.test.js
  src/components/layout/Tabs.js
  yarn.lock
Labels: CSS, Component

#286 feat(highchart): create function getTextStyle
  src/components/charts/LineChart.js
  src/components/charts/RadarChart.js
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Component

#288 feat(layout): apply eslint
  .eslintrc.js
  src/components/__tests__/Image.test.js
  src/components/layout/Footer.js
  src/components/layout/Heading.js
  src/components/layout/Image.js
  src/components/layout/Navbar.js
  src/components/layout/Tabs.js
Labels: Code clean, Component

#291 fix(table): support undefind, null
  src/components/__tests__/Table.test.js
  src/components/layout/Heading.js
  src/components/table/TBody.js
Labels: Component, bug

#292 Feature/version up.0.10.2
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
Labels: Build, bug

#293 릴리즈 v0.10.2
  .eslintrc.js
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
  src/components/__tests__/Image.test.js
  src/components/__tests__/Table.test.js
  src/components/__tests__/Tabs.test.js
  src/components/charts/LineChart.js
  src/components/charts/RadarChart.js
  src/components/layout/Footer.js
  src/components/layout/Heading.js
  src/components/layout/Image.js
  src/components/layout/Navbar.js
  src/components/layout/Tabs.js
  src/components/table/TBody.js
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
  yarn.lock
Labels: Build
