Repository linewalks/MDwalks-UI, pull requests merged in 2019-09, with the labels that each got.

#102 Create Layout Component
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  doczrc.js
  index.mdx
  package.json
  src/assets/styles/font.js
  src/assets/styles/variables.js
  src/components/layout/Footer.js
  src/components/layout/Heading.js
  src/components/layout/Image.js
  src/components/layout/Navbar.js
  src/components/table/TBody.js
  src/components/table/THead.js
  src/components/table/TableInfo.js
  src/docz/Layout.mdx
  src/docz/Table.mdx
  src/index.js
  yarn.lock
Labels: Component

#103 릴리즈. 0.4.1
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  doczrc.js
  index.mdx
  package.json
  src/assets/styles/font.js
  src/assets/styles/variables.js
  src/components/__tests__/SelectedCard.test.js
  src/components/card/SelectedCard.js
  src/components/layout/Footer.js
  src/components/layout/Heading.js
  src/components/layout/Image.js
  src/components/layout/Navbar.js
  src/components/table/TBody.js
  src/components/table/THead.js
  src/components/table/TableInfo.js
  src/docz/Layout.mdx
  src/docz/Table.mdx
  src/index.js
  yarn.lock
Labels: Component, test

#107 Apply Travis CI
  .travis.yml
Labels: CI

#105 Create Descriptions
  dist/index.esm.js
  dist/index.js
  index.mdx
  package.json
  src/components/__tests__/Descriptions.test.js
  src/components/table/Descriptions.js
  src/components/table/TableInfo.js
  src/docz/Table.mdx
  src/index.js
Labels: Component

#108 릴리즈.
  .travis.yml
  CHANGELOG.md
  LICENSE
  dist/index.esm.js
  dist/index.js
  index.mdx
  package.json
  src/components/__tests__/Descriptions.test.js
  src/components/table/Descriptions.js
  src/components/table/TableInfo.js
  src/docz/Table.mdx
  src/index.js
Labels: CI, Component

#111 arrow postion change to vertical center
  package.json
  src/assets/styles/font.js
  src/components/__tests__/SelectedCard.test.js
  src/components/card/SelectedCard.js
  yarn.lock
Labels: Component, test

#112 Create Test Code for SummaryCard
  src/assets/styles/font.js
  src/components/__tests__/SummaryCard.test.js
  src/components/card/SummaryCard.js
  src/docz/Card.mdx
Labels: Component, test

#117 Change base path of website
  docs/404.html
  docs/404/index.html
  docs/MDwalks-UI/index.html
  docs/MDwalks-UI/src-docz-card/index.html
  docs/MDwalks-UI/src-docz-charts/index.html
  docs/MDwalks-UI/src-docz-layout/index.html
  docs/MDwalks-UI/src-docz-table/index.html
  docs/app-068f57e891f163761e92.js
  docs/app-068f57e891f163761e92.js.map
  docs/chunk-map.json
  docs/commons-fe781d3762c0a6573fa2.js
  docs/commons-fe781d3762c0a6573fa2.js.map
  docs/page-data/404.html/page-data.json
  docs/page-data/404/page-data.json
  docs/page-data/MDwalks-UI/page-data.json
  docs/page-data/MDwalks-UI/src-docz-card/page-data.json
  docs/page-data/MDwalks-UI/src-docz-charts/page-data.json
  docs/page-data/MDwalks-UI/src-docz-layout/page-data.json
  docs/page-data/MDwalks-UI/src-docz-table/page-data.json
  docs/page-data/dev-404-page/page-data.json
  docs/page-data/index/page-data.json
  docs/page-data/src-docz-card/page-data.json
  docs/page-data/src-docz-charts/page-data.json
  docs/page-data/src-docz-layout/page-data.json
  docs/page-data/src-docz-table/page-data.json
  docs/static/d/1803957048.json
  docs/styles-ceebee8bd6c324fa8d5f.js
  docs/styles-ceebee8bd6c324fa8d5f.js.map
  docs/styles-df36f9e5d9f7291d9ac7.js
  docs/styles-df36f9e5d9f7291d9ac7.js.map
  docs/webpack.stats.json
  doczrc.js
Labels: docs

#118 릴리즈.
  docs/404.html
  docs/404/index.html
  docs/MDwalks-UI/index.html
  docs/MDwalks-UI/src-docz-card/index.html
  docs/MDwalks-UI/src-docz-charts/index.html
  docs/MDwalks-UI/src-docz-layout/index.html
  docs/MDwalks-UI/src-docz-table/index.html
  docs/app-068f57e891f163761e92.js
  docs/app-068f57e891f163761e92.js.map
  docs/chunk-map.json
  docs/commons-fe781d3762c0a6573fa2.js
  docs/commons-fe781d3762c0a6573fa2.js.map
  docs/page-data/404.html/page-data.json
  docs/page-data/404/page-data.json
  docs/page-data/MDwalks-UI/page-data.json
  docs/page-data/MDwalks-UI/src-docz-card/page-data.json
  docs/page-data/MDwalks-UI/src-docz-charts/page-data.json
  docs/page-data/MDwalks-UI/src-docz-layout/page-data.json
  docs/page-data/MDwalks-UI/src-docz-table/page-data.json
  docs/page-data/dev-404-page/page-data.json
  docs/page-data/index/page-data.json
  docs/page-data/src-docz-card/page-data.json
  docs/page-data/src-docz-charts/page-data.json
  docs/page-data/src-docz-layout/page-data.json
  docs/page-data/src-docz-table/page-data.json
  docs/static/d/1803957048.json
  docs/styles-ceebee8bd6c324fa8d5f.js
  docs/styles-ceebee8bd6c324fa8d5f.js.map
  docs/styles-df36f9e5d9f7291d9ac7.js
  docs/styles-df36f9e5d9f7291d9ac7.js.map
  docs/webpack.stats.json
  doczrc.js
Labels: docs

#122 Create colspan in Descriptions
  package.json
  src/components/__tests__/Descriptions.test.js
  src/components/table/Descriptions.js
  src/docz/Table.mdx
Labels: Component, docs

#126 Update variables
  src/assets/styles/form.sass
  src/assets/styles/variables.js
  src/assets/styles/variables.sass
Labels: CSS

#127 Build v0.4.3
  .travis.yml
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/404.html
  docs/404/index.html
  docs/app-566542973b1c41c339c8.js
  docs/app-566542973b1c41c339c8.js.map
  docs/chunk-map.json
  docs/commons-23255119acaafcd9d900.js
  docs/commons-23255119acaafcd9d900.js.map
  docs/commons-255b5feaa399da67fa0a.js
  docs/commons-255b5feaa399da67fa0a.js.map
  docs/commons-fd870ea0bfdcb6f81373.js
  docs/commons-fd870ea0bfdcb6f81373.js.map
  docs/component---src-docz-layout-mdx-79f250b2d6d552e83343.js
  docs/component---src-docz-layout-mdx-79f250b2d6d552e83343.js.map
  docs/component---src-docz-table-mdx-b1148bb497e78619f3a7.js
  docs/component---src-docz-table-mdx-b1148bb497e78619f3a7.js.map
  docs/component---src-docz-table-mdx-cee8977eb5d9bec7e729.js
  docs/component---src-docz-table-mdx-cee8977eb5d9bec7e729.js.map
  docs/index.html
  docs/page-data/404.html/page-data.json
  docs/page-data/404/page-data.json
  docs/page-data/dev-404-page/page-data.json
  docs/page-data/index/page-data.json
  docs/page-data/src-docz-card/page-data.json
  docs/page-data/src-docz-charts/page-data.json
  docs/page-data/src-docz-layout/page-data.json
  docs/page-data/src-docz-table/page-data.json
  docs/src-docz-card/index.html
  docs/src-docz-charts/index.html
  docs/src-docz-layout/index.html
  docs/src-docz-table/index.html
  docs/static/d/1803957048.json
  docs/styles-1e59fd1cee517b18a8d2.js
  docs/styles-1e59fd1cee517b18a8d2.js.map
  docs/styles-6485fc6e262e76dcaab7.js
  docs/styles-6485fc6e262e76dcaab7.js.map
  docs/styles-ff4065bffe41657c2e89.js
  docs/styles-ff4065bffe41657c2e89.js.map
  docs/webpack-runtime-c337c739b005d5353c4a.js
  docs/webpack-runtime-c337c739b005d5353c4a.js.map
  docs/webpack-runtime-cc3beff1ce5cef73ed49.js
  docs/webpack-runtime-cc3beff1ce5cef73ed49.js.map
  docs/webpack.stats.json
  package.json
Labels: Build, CI

#128 Release v0.4.3
  .travis.yml
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/404.html
  docs/404/index.html
  docs/app-566542973b1c41c339c8.js
  docs/app-566542973b1c41c339c8.js.map
  docs/chunk-map.json
  docs/commons-23255119acaafcd9d900.js
  docs/commons-23255119acaafcd9d900.js.map
  docs/commons-255b5feaa399da67fa0a.js
  docs/commons-255b5feaa399da67fa0a.js.map
  docs/commons-fd870ea0bfdcb6f81373.js
  docs/commons-fd870ea0bfdcb6f81373.js.map
  docs/component---src-docz-layout-mdx-79f250b2d6d552e83343.js
  docs/component---src-docz-layout-mdx-79f250b2d6d552e83343.js.map
  docs/component---src-docz-table-mdx-b1148bb497e78619f3a7.js
  docs/component---src-docz-table-mdx-b1148bb497e78619f3a7.js.map
  docs/component---src-docz-table-mdx-cee8977eb5d9bec7e729.js
  docs/component---src-docz-table-mdx-cee8977eb5d9bec7e729.js.map
  docs/index.html
  docs/page-data/404.html/page-data.json
  docs/page-data/404/page-data.json
  docs/page-data/dev-404-page/page-data.json
  docs/page-data/index/page-data.json
  docs/page-data/src-docz-card/page-data.json
  docs/page-data/src-docz-charts/page-data.json
  docs/page-data/src-docz-layout/page-data.json
  docs/page-data/src-docz-table/page-data.json
  docs/src-docz-card/index.html
  docs/src-docz-charts/index.html
  docs/src-docz-layout/index.html
  docs/src-docz-table/index.html
  docs/static/d/1803957048.json
  docs/styles-1e59fd1cee517b18a8d2.js
  docs/styles-1e59fd1cee517b18a8d2.js.map
  docs/styles-6485fc6e262e76dcaab7.js
  docs/styles-6485fc6e262e76dcaab7.js.map
  docs/styles-ff4065bffe41657c2e89.js
  docs/styles-ff4065bffe41657c2e89.js.map
  docs/webpack-runtime-c337c739b005d5353c4a.js
  docs/webpack-runtime-c337c739b005d5353c4a.js.map
  docs/webpack-runtime-cc3beff1ce5cef73ed49.js
  docs/webpack-runtime-cc3beff1ce5cef73ed49.js.map
  docs/webpack.stats.json
  package.json
  src/assets/styles/form.sass
  src/assets/styles/variables.js
  src/assets/styles/variables.sass
  src/components/__tests__/Descriptions.test.js
  src/components/table/Descriptions.js
  src/docz/Table.mdx
Labels: Build

#130 Resolve Warning of React
  CHANGELOG.md
  index.mdx
  src/components/table/Descriptions.js
Labels: Component, bug

#132 Feature/paper.jamia docz
  dist/index.esm.js
  dist/index.js
  src/components/paper/Heatmap.js
Labels: docs

#133 Update docz
  docs/404.html
  docs/404/index.html
  docs/MDwalks-UI/index.html
  docs/MDwalks-UI/src-docz-card/index.html
  docs/MDwalks-UI/src-docz-charts/index.html
  docs/MDwalks-UI/src-docz-layout/index.html
  docs/MDwalks-UI/src-docz-paper/index.html
  docs/MDwalks-UI/src-docz-table/index.html
  docs/app-6be42d8b356c7aef3a91.js
  docs/app-6be42d8b356c7aef3a91.js.map
  docs/chunk-map.json
  docs/commons-dbb0b7dd1bfc82261268.js
  docs/commons-dbb0b7dd1bfc82261268.js.map
  docs/component---index-mdx-e433684183957d4eb862.js
  docs/component---index-mdx-e433684183957d4eb862.js.map
  docs/component---src-docz-card-mdx-6cd67239f037ca9380ce.js
  docs/component---src-docz-card-mdx-6cd67239f037ca9380ce.js.map
  docs/component---src-docz-charts-mdx-46edf68e076782d44226.js
  docs/component---src-docz-charts-mdx-46edf68e076782d44226.js.map
  docs/component---src-docz-layout-mdx-e2376660dd2794995b7f.js
  docs/component---src-docz-layout-mdx-e2376660dd2794995b7f.js.map
  docs/component---src-docz-paper-mdx-18704b19ca1e79ce8026.js
  docs/component---src-docz-paper-mdx-18704b19ca1e79ce8026.js.map
  docs/component---src-docz-table-mdx-53e54ab85130dbbc8bde.js
  docs/component---src-docz-table-mdx-53e54ab85130dbbc8bde.js.map
  docs/component---src-pages-404-js-fc193d8d6798ee58695b.js
  docs/component---src-pages-404-js-fc193d8d6798ee58695b.js.map
  docs/page-data/404.html/page-data.json
  docs/page-data/404/page-data.json
  docs/page-data/MDwalks-UI/page-data.json
  docs/page-data/MDwalks-UI/src-docz-card/page-data.json
  docs/page-data/MDwalks-UI/src-docz-charts/page-data.json
  docs/page-data/MDwalks-UI/src-docz-layout/page-data.json
  docs/page-data/MDwalks-UI/src-docz-paper/page-data.json
  docs/page-data/MDwalks-UI/src-docz-table/page-data.json
  docs/page-data/dev-404-page/page-data.json
  docs/page-data/index/page-data.json
  docs/page-data/src-docz-card/page-data.json
  docs/page-data/src-docz-charts/page-data.json
  docs/page-data/src-docz-table/page-data.json
  docs/static/d/1803957048.json
  docs/styles-a6c1cfedaa82bae6ccd0.js
  docs/styles-a6c1cfedaa82bae6ccd0.js.map
  docs/webpack-runtime-b19e2d931311de1e9d09.js
  docs/webpack-runtime-b19e2d931311de1e9d09.js.map
  docs/webpack.stats.json
Labels: docs

#137 Create chartUtility.test.js
  src/helper/chartUtility.test.js
Labels: DONE, test

#138 Apply module.export to variables, charUtilty
  CHANGELOG.md
  src/assets/styles/variables.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/SankeyChart.js
  src/components/charts/Timeline.js
  src/components/table/THead.js
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Build, Component

#139 Release 0.4.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/styles/variables.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/SankeyChart.js
  src/components/charts/Timeline.js
  src/components/table/THead.js
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Component

#142 fixed: Warning on Description
  CHANGELOG.md
  src/components/table/Descriptions.js
Labels: Component, bug

#140 Test Code for SankeyChart with snapshot
  .gitignore
  README.md
  package.json
  src/components/__tests__/SankeyChart.test.js
  src/components/__tests__/__snapshots__/SankeyChart.test.js.snap
  src/components/charts/SankeyChart.js
  src/docz/Charts.mdx
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
  yarn.lock
Labels: test

#144 build v0.4.5
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
Labels: Build

#143 Release 0.4.5 Component
  .gitignore
  CHANGELOG.md
  README.md
  dist/index.esm.js
  dist/index.js
  package.json
  src/components/__tests__/SankeyChart.test.js
  src/components/__tests__/__snapshots__/SankeyChart.test.js.snap
  src/components/charts/SankeyChart.js
  src/components/table/Descriptions.js
  src/docz/Charts.mdx
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
  yarn.lock
Labels: Component

#147 Fix change method that request to import on chartUtiltity
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  src/assets/styles/index.js
  src/assets/styles/variables.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/SankeyChart.js
  src/components/charts/Timeline.js
  src/components/table/THead.js
  src/helper/chartUtility.js
  src/helper/index.js
Labels: Component, bug

#149 Revert "Revert "Release 0.4.5 Component""
  .gitignore
  CHANGELOG.md
  README.md
  dist/index.esm.js
  dist/index.js
  package.json
  src/components/__tests__/SankeyChart.test.js
  src/components/__tests__/__snapshots__/SankeyChart.test.js.snap
  src/components/charts/SankeyChart.js
  src/components/table/Descriptions.js
  src/docz/Charts.mdx
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
  yarn.lock
Labels: CI, Component, bug

#150 Release 0.4.5
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  src/assets/styles/index.js
  src/assets/styles/variables.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/SankeyChart.js
  src/components/charts/Timeline.js
  src/components/table/THead.js
  src/helper/chartUtility.js
  src/helper/index.js
Labels: Build, Component

#152 Append property that colWidth on Descriptions
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  src/components/__tests__/Descriptions.test.js
  src/components/table/Descriptions.js
Labels: Build, Component

#154 Feature/issue.153
  dist/index.esm.js
  dist/index.js
  src/components/charts/SankeyChart.js
  src/docz/Charts.mdx
Labels: Component, bug

#155 Update changelog
  CHANGELOG.md
Labels: Component

#156 Release 0.4.7
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  src/components/__tests__/Descriptions.test.js
  src/components/charts/SankeyChart.js
  src/components/table/Descriptions.js
  src/docz/Charts.mdx
Labels: Build, Component

#157 Clean Charts.mdx
  package.json
  src/docz/Charts.mdx
Labels: Component
