Repository linewalks/MDwalks-UI, pull requests merged in 2019-10, with the labels that each got.

#166 Update Changlog to 0.5.1
  CHANGELOG.md
Labels: docs

#162 Add beta menu for paper.jamia
  doczrc.js
  src/components/card/SelectedCard.js
  src/components/paper/Heatmap.js
  src/data/dataForHeatmapDayCls.js
  src/data/dataForHeatmapDiff.js
  src/data/dataForHeatmapSinglePatient.js
  src/docz/Paper.mdx
Labels: docs

#170 Rename button components
  src/components/button/Button.js
  src/docz/Button.mdx
Labels: Component, docs

#173 Insert chartUtility in src/index.js
  dist/index.esm.js
  dist/index.js
  src/helper/index.js
  src/index.js
Labels: Component, bug

#174 Update Changelog
  CHANGELOG.md
Labels: Component, bug

#179 Feature/issue.178
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
  src/assets/styles/reset.css
  src/assets/styles/variables.js
  src/assets/svg/EventSummary/a.i._analysis_features-hover.svg
  src/assets/svg/EventSummary/a.i._analysis_features.svg
  src/assets/svg/EventSummary/average_length_of_stay.svg
  src/assets/svg/EventSummary/average_mortality_rate.svg
  src/assets/svg/EventSummary/event_occurrence.svg
  src/assets/svg/EventSummary/follow-up_patients-hover.svg
  src/assets/svg/EventSummary/follow-up_patients.svg
  src/assets/svg/EventSummary/high_risk_patients-hover.svg
  src/assets/svg/EventSummary/high_risk_patients.svg
  src/assets/svg/EventSummary/number_of_patients.svg
  src/assets/svg/EventSummary/total_patients-hover.svg
  src/assets/svg/EventSummary/total_patients.svg
  src/assets/svg/icn_popup_close_md.svg
  src/components/__tests__/Modal.test.js
  src/components/modal/Modal.js
  src/docz/Modal.mdx
  src/index.js
Labels: Component

#180 릴리즈 0.6.1
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
  src/assets/styles/reset.css
  src/assets/styles/variables.js
  src/assets/svg/EventSummary/a.i._analysis_features-hover.svg
  src/assets/svg/EventSummary/a.i._analysis_features.svg
  src/assets/svg/EventSummary/average_length_of_stay.svg
  src/assets/svg/EventSummary/average_mortality_rate.svg
  src/assets/svg/EventSummary/event_occurrence.svg
  src/assets/svg/EventSummary/follow-up_patients-hover.svg
  src/assets/svg/EventSummary/follow-up_patients.svg
  src/assets/svg/EventSummary/high_risk_patients-hover.svg
  src/assets/svg/EventSummary/high_risk_patients.svg
  src/assets/svg/EventSummary/number_of_patients.svg
  src/assets/svg/EventSummary/total_patients-hover.svg
  src/assets/svg/EventSummary/total_patients.svg
  src/assets/svg/icn_popup_close_md.svg
  src/components/__tests__/Modal.test.js
  src/components/modal/Modal.js
  src/docz/Modal.mdx
  src/index.js
Labels: Build, Component

#182 Modify Style of Button, Modal
  CHANGELOG.md
  doczrc.js
  src/components/__tests__/Modal.test.js
  src/components/button/Button.js
  src/components/layout/Heading.js
  src/components/modal/Modal.js
Labels: Component

#190 Feature/build.v0.6.2
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/404.html
  docs/404/index.html
  docs/app-e58e593c65f3e3421947.js
  docs/app-e58e593c65f3e3421947.js.map
  docs/chunk-map.json
  docs/commons-820bac9ca8dcc38182bc.js
  docs/commons-820bac9ca8dcc38182bc.js.map
  docs/component---index-mdx-82ec239c83a8b2a9bf06.js
  docs/component---index-mdx-82ec239c83a8b2a9bf06.js.map
  docs/component---src-docz-button-mdx-82154b5ef15b04b319ff.js
  docs/component---src-docz-button-mdx-82154b5ef15b04b319ff.js.map
  docs/component---src-docz-card-mdx-503f5badc1f4cc7f211b.js
  docs/component---src-docz-card-mdx-503f5badc1f4cc7f211b.js.map
  docs/component---src-docz-charts-mdx-6f5286c6ec7c9b679dc9.js
  docs/component---src-docz-charts-mdx-6f5286c6ec7c9b679dc9.js.map
  docs/component---src-docz-layout-mdx-3d489afc3784e447ee38.js
  docs/component---src-docz-layout-mdx-3d489afc3784e447ee38.js.map
  docs/component---src-docz-modal-mdx-0805ec2c60045547a4ec.js
  docs/component---src-docz-modal-mdx-0805ec2c60045547a4ec.js.map
  docs/component---src-docz-paper-mdx-ce71b6f84f31e039353e.js
  docs/component---src-docz-paper-mdx-ce71b6f84f31e039353e.js.map
  docs/component---src-docz-table-mdx-bd7e58f913031bae83d1.js
  docs/component---src-docz-table-mdx-bd7e58f913031bae83d1.js.map
  docs/component---src-pages-404-js-119932591d344a777bc7.js
  docs/component---src-pages-404-js-119932591d344a777bc7.js.map
  docs/index.html
  docs/page-data/404.html/page-data.json
  docs/page-data/404/page-data.json
  docs/page-data/changelog/page-data.json
  docs/page-data/dev-404-page/page-data.json
  docs/page-data/index/page-data.json
  docs/page-data/readme/page-data.json
  docs/page-data/src-docz-button/page-data.json
  docs/page-data/src-docz-card/page-data.json
  docs/page-data/src-docz-charts/page-data.json
  docs/page-data/src-docz-layout/page-data.json
  docs/page-data/src-docz-modal/page-data.json
  docs/page-data/src-docz-paper/page-data.json
  docs/page-data/src-docz-table/page-data.json
  docs/src-docz-button/index.html
  docs/src-docz-card/index.html
  docs/src-docz-charts/index.html
  docs/src-docz-layout/index.html
  docs/src-docz-modal/index.html
  docs/src-docz-paper/index.html
  docs/src-docz-table/index.html
  docs/static/d/1803957048.json
  docs/styles-0a6506e5cb6f84c614a1.js
  docs/styles-0a6506e5cb6f84c614a1.js.map
  docs/styles.47390d20a7abb2819a03.css
  docs/styles.efe1dfa9920c50f6729d.css
  docs/webpack-runtime-673f28deed9444c8507f.js
  docs/webpack-runtime-673f28deed9444c8507f.js.map
  docs/webpack.stats.json
Labels: CSS, Component, docs

#185 add histogram chart and test
  dist/index.esm.js
  dist/index.js
  index.mdx
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.css
  src/components/charts/Histogram.js
  src/docz/Charts.mdx
  src/index.js
Labels: Component, DONE, test

#189 remove css width in constructor and add css width div tag
  dist/index.esm.js
  dist/index.js
  src/components/charts/BarGauge.js
Labels: Component, DONE, bug

#197 test that checking domain, tickValues in Histogram.test.js
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.js
Labels: Component, DONE, test

#196 add scoreClickEventHandler
  dist/index.esm.js
  dist/index.js
  src/components/__tests__/LineMergeTimeline.test.js
  src/components/charts/LineMergeTimeline.js
Labels: Component, DONE

#205 Create wrapTh function in table component
  src/components/__tests__/Table.test.js
  src/components/table/THead.js
Labels: Component

#199 Create CheckList Component
  doczrc.js
  src/components/list/CheckList.js
  src/components/list/CheckList.test.js
  src/components/list/icn-add-sm.svg
  src/docz/List.mdx
  src/index.js
  yarn.lock
Labels: Component, DONE, docs, test

#203 LineChart - 요약카드 차트에 맞는 리팩토링
  dist/index.esm.js
  dist/index.js
  src/components/__tests__/LineChart.test.js
  src/components/charts/LineChart.js
Labels: Component, DONE

#209 Reactoring table.js
  package.json
  src/components/table/TBody.js
  src/components/table/TFoot.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/docz/Table.mdx
  yarn.lock
Labels: Component

#214 Fix: table
  src/components/table/TFoot.js
  src/components/table/THead.js
  src/components/table/Table.js
Labels: CSS, Component, bug

#215 방문시점별 위험도와 가중치 이벤트 커서추가
  dist/index.esm.js
  dist/index.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/LineMergeTimeline.module.css
Labels: CSS, Component, DONE

#217 Order checked to onChange
  src/assets/styles/font.js
  src/components/list/CheckList.js
  src/components/list/CheckList.test.js
Labels: Component, test

#223 Feature/issue.222
  src/assets/styles/variables.js
  src/components/modal/Modal.js
  src/docz/Modal.mdx
Labels: Component

#227 MACE 위험도 차트의 선과 점 불일치
  src/components/charts/LineMergeTimeline.js
Labels: Component, DONE, bug

#229 요약카드 차트 폰트 크기, 가로선 간격 수정
  src/components/charts/LineChart.js
Labels: CSS, DONE

#225 레이더차트 및 테스트 추가
  src/components/__tests__/RadarChart.test.js
  src/components/charts/RadarChart.js
  src/docz/Charts.mdx
  src/index.js
Labels: Component, DONE, test
