Repository linewalks/MDwalks-UI, pull requests merged in 2020-02, with the labels that each got.

#367 v0.12.4
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#371 feat(docz): prototype react-styleguidist
  package.json
  src/components/button/ButtonLink.md
  src/components/card/SelectedCard.md
  src/components/card/SummaryCard.md
  src/components/charts/BarGauge.md
  src/components/charts/LineChart.md
  src/components/charts/SankeyChart.md
  src/components/modal/Modal.md
  webpack.config.js
  yarn.lock
Labels: docs

#368 feat: ToggleLargeButton Component와 test 추가
  package.json
  src/components/button/ToggleLargeButton.js
  src/components/button/ToggleLargeButton.md
  src/components/button/ToggleLargeButton.test.js
Labels: Component

#373 feat: CDM BarChart를 MDwalks-UI로 Migration
  package.json
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/TooltipBox.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/common/cdmCommon.js
  src/components/modal/Modal.md
  src/components/tooltip/TooltipBox.js
  src/index.js
  styleguide.config.js
  webpack.config.js
  yarn.lock
Labels: Component

#376 improvement(refactor): CDM BarChart를 활용한 LineChart refactoring
  .babelrc
  .eslintrc.js
  gatsby-node.js
  package.json
  src/components/__tests__/LineChart.test.js
  src/components/charts/.eslintrc.js
  src/components/charts/BarChart.js
  src/components/charts/LineChart.js
  src/components/charts/LineChart.md
  webpack.config.js
Labels: Component

#379 v0.13.1
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#383 improvement(TooltipBox): remove showOrigin
  src/components/__tests__/TooltipBox.test.js
  src/components/tooltip/TooltipBox.js
Labels: Component

#384 style(BarChart): remove BoxShadow
  src/components/charts/BarChart.js
  src/components/charts/LineChart.js
  src/components/common/cdmCommon.js
Labels: Component

#385 Feature/issue.380
  src/components/__tests__/SummaryCard.test.js
  src/components/card/SummaryCard.js
Labels: Component

#386 v0.13.2
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#390 Feature/issue.389
  src/__tests__/index.test.js
  src/index.js
Labels: Component

#391 v0.13.3
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#396 feat(TooltipBox): modify convert option
  src/components/__tests__/TooltipBox.test.js
  src/components/tooltip/TooltipBox.js
Labels: Component

#398 fix(Sankey): Sankey Chart 데이터 변경시 렌더링이 안됨
  package.json
  rollup.config.js
  src/components/__tests__/SankeyChart.test.js
  src/components/charts/SankeyChart.js
  yarn.lock
Labels: bug

#399 v0.13.5
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#402 fix(Sankey): SankeyChart 초기값문제
  rollup.config.js
  src/components/__tests__/SankeyChart.test.js
  src/components/charts/SankeyChart.js
  src/components/list/CheckList.js
  src/components/list/RadioList.js
Labels: bug

#404 improvement(chart): eslint
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/BarGauge.test.js
  src/components/__tests__/Histogram.test.js
  src/components/__tests__/LineMergeTimeline.test.js
  src/components/charts/BarGauge.js
  src/components/charts/Histogram.js
  src/components/charts/LineMergeTimeline.js
Labels: eslint

#407 fix(Histogram): render
  src/components/charts/Histogram.js
  src/components/charts/Histogram.md
  src/components/charts/LineMergeTimeline.md
Labels: Component

#409 v0.13.6
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#411 fix: Chart 자잘한 bug 수정
  src/components/__tests__/SankeyChart.test.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/SankeyChart.js
Labels: bug

#412 v0.13.7
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#413 feat(styleguide): update components
  src/components/__tests__/Image.test.js
  src/components/button/Button.js
  src/components/button/Button.md
  src/components/button/Button.test.js
  src/components/button/ButtonLink.js
  src/components/button/ButtonLink.test.js
  src/components/button/ButtonTextLink.js
  src/components/button/ButtonTextLink.md
  src/components/button/ButtonTextLink.test.js
  src/components/button/ToggleButton.md
  src/components/charts/LineMergeTimeline.md
  src/components/charts/RadarChart.md
  src/components/charts/RadiusGauge.md
  src/components/charts/SankeyChart.md
  src/components/charts/TimeToEvent.md
  src/components/charts/Timeline.md
  src/components/charts/TreeMap.md
  src/components/common/cdmCommon.md
  src/components/form/SelectBox.md
  src/components/layout/Footer.md
  src/components/layout/Heading.md
  src/components/layout/Image.js
  src/components/layout/Image.md
  src/components/layout/Navbar.md
  src/components/layout/Tabs.md
  src/components/list/CheckList.md
  src/components/list/RadioList.md
  src/components/modal/Modal.md
  src/components/pagination/Pagination.md
  src/components/paper/Heatmap.js
  src/components/paper/Heatmap.md
  src/components/paper/Sequence.md
  src/components/table/Descriptions.md
  src/components/table/EmptyPlaceHolder.md
  src/components/table/Table.md
  src/components/toast/Toast.md
  src/docz/Button.mdx
  src/docz/Layout.mdx
  src/index.js
  styleguide.config.js
Labels: docs
