Repository linewalks/MDwalks-UI, pull requests merged in 2020-03, with the labels that each got.

#420 Feature/issue.405
  dist/index.esm.js
  dist/index.js
  package.json
  src/components/__tests__/RadarChart.test.js
  src/components/__tests__/RadiusGauge.test.js
  src/components/__tests__/SankeyChart.test.js
  src/components/charts/RadarChart.js
  src/components/charts/RadiusGauge.js
  src/components/charts/SankeyChart.js
  src/components/charts/Timeline.js
Labels: eslint

#419 improvement(chart): apply eslint
  .eslintignore
  package.json
  src/components/__tests__/LineMergeTimeline.test.js
  src/components/__tests__/Modal.test.js
  src/components/__tests__/Pagination.test.js
  src/components/__tests__/SelectedCard.test.js
  src/components/__tests__/TimeToEvent.test.js
  src/components/__tests__/TreeMap.test.js
  src/components/button/ToggleButton.test.js
  src/components/button/ToggleLargeButton.test.js
  src/components/card/SelectedCard.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/TimeToEvent.js
  src/components/charts/TimeToEvent.module.css
  src/components/charts/TreeMap.js
  src/components/list/CheckList.js
  src/components/list/RadioList.js
  src/components/modal/Modal.js
Labels: eslint

#421 improvement(components): apply eslint
  package.json
  src/components/__tests__/Descriptions.test.js
  src/components/__tests__/LineChart.test.js
  src/components/__tests__/Modal.test.js
  src/components/__tests__/Pagination.test.js
  src/components/__tests__/SelectedCard.test.js
  src/components/__tests__/TFoot.test.js
  src/components/__tests__/THead.test.js
  src/components/__tests__/Table.test.js
  src/components/button/ButtonLink.js
  src/components/button/ButtonTextLink.js
  src/components/form/SelectBox.js
  src/components/modal/Modal.js
  src/components/pagination/Pagination.js
  src/components/paper/Heatmap.js
  src/components/paper/Sequence.js
  src/components/table/Descriptions.js
  src/components/table/EmptyPlaceHolder.js
  src/components/table/TBody.js
  src/components/table/TFoot.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/components/table/Table.md
Labels: eslint

#424 style(footer): remove padding
  src/components/layout/Footer.js
Labels: Component

#427 style(Tab): modify padding, color
  src/assets/styles/variables.js
  src/assets/styles/variables.sass
  src/components/__tests__/Tabs.test.js
  src/components/layout/Tabs.js
  src/components/layout/Tabs.md
Labels: Component

#428 Feature/issue.426
  package.json
  src/__tests__/index.test.js
  src/components/__tests__/LineMergeTimeline.test.js
  src/components/button/ButtonLink.md
  src/components/button/ButtonTextLink.md
  src/components/button/TextLink.js
  src/components/button/TextLink.md
  src/components/button/TextLink.test.js
  src/index.js
Labels: Component

#430 feat(TextLink): insert icon style
  src/components/button/TextLink.js
  src/components/button/TextLink.md
  src/components/button/TextLink.test.js
Labels: Component

#433 feat(ToggleButton): add lg size, change color set
  src/assets/styles/font.sass
  src/components/button/ToggleButton.js
  src/components/button/ToggleButton.md
  src/components/button/ToggleLargeButton.md
Labels: Component

#431 v0.13.8
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.2306f369.js
  docs/build/bundle.a9a3f1ea.js
  docs/build/bundle.a9a3f1ea.js.LICENSE.txt
  docs/index.html
  package.json
Labels: Build

#436 Feature/issue.435
  src/assets/svg/pagination/btn_next_sm.svg
  src/assets/svg/pagination/btn_pre_sm.svg
  src/components/__tests__/Pagination.test.js
  src/components/pagination/Input.js
  src/components/pagination/Pagination.js
  src/components/pagination/Pagination.md
  styleguide.config.js
Labels: Component

#438 style(Button): change color
  src/components/button/Button.js
  src/components/button/Button.md
  src/components/button/Button.test.js
Labels: Component

#439 v0.13.9
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Component

#440 docs: Update v0.13.9
  docs/build/bundle.a9a3f1ea.js
  docs/build/bundle.a9ba24cf.js
  docs/build/bundle.a9ba24cf.js.LICENSE.txt
  docs/index.html
  docs/static/media/btn_next_sm.11d1d209.svg
  docs/static/media/btn_pre_sm.ce1a32f7.svg
  package.json
Labels: Build

#445 fix(Input): only number
  package.json
  setupTest.js
  src/components/__tests__/Input.test.js
  src/components/pagination/Input.js
  yarn.lock
Labels: bug

#448 improvement(TextLink): add props that href, target, rel
  src/components/button/TextLink.js
Labels: Component

#449 fix(TextLink): rename styled to style
  src/components/button/TextLink.js
Labels: Component

#450 Feature/version.up.v0.13.10
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.7350e039.js
  docs/build/bundle.7350e039.js.LICENSE.txt
  docs/build/bundle.a9ba24cf.js
  docs/index.html
  package.json
Labels: Build

#453 fix(TextLink): set hover color
  src/components/button/TextLink.js
Labels: Component, bug

#456 style(font): add fc
  src/assets/styles/font.sass
Labels: CSS

#457 Feature/issue.443
  src/assets/svg/table/icn_sort_down_default.svg
  src/assets/svg/table/icn_sort_down_disable.svg
  src/assets/svg/table/icn_sort_down_focus.svg
  src/assets/svg/table/icn_sort_up_default.svg
  src/assets/svg/table/icn_sort_up_disable.svg
  src/assets/svg/table/icn_sort_up_focus.svg
  src/components/__tests__/THead.test.js
  src/components/__tests__/Table.test.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/components/table/Table.md
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Component

#458 Feature/issue.451
  package.json
  src/components/__tests__/Table.test.js
  src/components/table/Columns.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/components/table/Table.md
  yarn.lock
Labels: Component

#459 v0.13.11
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.7350e039.js
  docs/build/bundle.b56affd7.js
  docs/build/bundle.b56affd7.js.LICENSE.txt
  docs/index.html
  docs/static/media/icn_sort_down_default.b2f42f0f.svg
  docs/static/media/icn_sort_down_disable.59d7432c.svg
  docs/static/media/icn_sort_down_focus.60616432.svg
  docs/static/media/icn_sort_up_default.64bb60dd.svg
  docs/static/media/icn_sort_up_disable.4f179495.svg
  docs/static/media/icn_sort_up_focus.82c80c59.svg
  package.json
Labels: Build

#460 v0.13.11
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.a9ba24cf.js
  docs/build/bundle.b56affd7.js
  docs/build/bundle.b56affd7.js.LICENSE.txt
  docs/index.html
  docs/static/media/icn_sort_down_default.b2f42f0f.svg
  docs/static/media/icn_sort_down_disable.59d7432c.svg
  docs/static/media/icn_sort_down_focus.60616432.svg
  docs/static/media/icn_sort_up_default.64bb60dd.svg
  docs/static/media/icn_sort_up_disable.4f179495.svg
  docs/static/media/icn_sort_up_focus.82c80c59.svg
  package.json
  setupTest.js
  src/assets/styles/font.sass
  src/assets/svg/table/icn_sort_down_default.svg
  src/assets/svg/table/icn_sort_down_disable.svg
  src/assets/svg/table/icn_sort_down_focus.svg
  src/assets/svg/table/icn_sort_up_default.svg
  src/assets/svg/table/icn_sort_up_disable.svg
  src/assets/svg/table/icn_sort_up_focus.svg
  src/components/__tests__/Input.test.js
  src/components/__tests__/THead.test.js
  src/components/__tests__/Table.test.js
  src/components/button/TextLink.js
  src/components/pagination/Input.js
  src/components/table/Columns.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/components/table/Table.md
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
  yarn.lock
Labels: Build

#464 feat(BarChart): add prop of layout(horizontal, vertical)
  src/components/__tests__/BarChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
Labels: Component

#467 feat(BarChart): add prop of stackId
  src/components/__tests__/BarChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
Labels: Component

#470 fix(THead): rollback style of th
  src/components/table/THead.js
  styleguide.config.js
Labels: bug, style

#471 feat(Pagination): add prop of align
  src/components/pagination/Pagination.js
  src/components/pagination/Pagination.md
Labels: Component

#474 feat(docs): apply SpoqaHanSans
  src/assets/fonts/SpoqaHanSansBold.ttf
  src/assets/fonts/SpoqaHanSansBold.woff
  src/assets/fonts/SpoqaHanSansBold.woff2
  src/assets/fonts/SpoqaHanSansLight.ttf
  src/assets/fonts/SpoqaHanSansLight.woff
  src/assets/fonts/SpoqaHanSansLight.woff2
  src/assets/fonts/SpoqaHanSansRegular.ttf
  src/assets/fonts/SpoqaHanSansRegular.woff
  src/assets/fonts/SpoqaHanSansRegular.woff2
  src/assets/fonts/SpoqaHanSansThin.ttf
  src/assets/fonts/SpoqaHanSansThin.woff
  src/assets/fonts/SpoqaHanSansThin.woff2
  src/assets/styles/spoqaHansans.css
  styleguide.config.js
Labels: docs

#477 style(Tabs): modify padding-bottom
  src/components/layout/Tabs.js
Labels: style

#481 fix(Thead): set font-size of sort button
  src/components/table/THead.js
Labels: CSS, bug

#482 docs: remove docz
  README.md
  docs/build/bundle.487677c7.js
  docs/build/bundle.8cb2d5d5.js
  docs/build/bundle.8cb2d5d5.js.LICENSE.txt
  docs/index.html
  doczrc.js
  gatsby-node.js
  index.mdx
  package.json
  src/docz/Button.mdx
  src/docz/Card.mdx
  src/docz/Charts.mdx
  src/docz/Layout.mdx
  src/docz/List.mdx
  src/docz/Modal.mdx
  src/docz/Pagenation.mdx
  src/docz/Paper.mdx
  src/docz/Table.mdx
  src/docz/Toast.mdx
  src/docz/custom.css
  src/docz/form.mdx
  yarn.lock
Labels: docs

#484 feat(RadioBox): create
  src/__tests__/index.test.js
  src/components/form/RadioBox.js
  src/components/form/RadioBox.md
  src/components/pagination/Pagination.js
  src/components/toast/Toast.md
  src/index.js
Labels: Component

#485 v0.13.13
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#486 v0.13.13
  CHANGELOG.md
  README.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.487677c7.js
  docs/build/bundle.8cb2d5d5.js
  docs/build/bundle.8cb2d5d5.js.LICENSE.txt
  docs/index.html
  doczrc.js
  gatsby-node.js
  index.mdx
  package.json
  src/__tests__/index.test.js
  src/components/form/RadioBox.js
  src/components/form/RadioBox.md
  src/components/pagination/Pagination.js
  src/components/table/THead.js
  src/components/toast/Toast.md
  src/docz/Button.mdx
  src/docz/Card.mdx
  src/docz/Charts.mdx
  src/docz/Layout.mdx
  src/docz/List.mdx
  src/docz/Modal.mdx
  src/docz/Pagenation.mdx
  src/docz/Paper.mdx
  src/docz/Table.mdx
  src/docz/Toast.mdx
  src/docz/custom.css
  src/docz/form.mdx
  src/index.js
  yarn.lock
Labels: Build

#489 improvement: Histogram tooltip 제거 및 평균선에 Average Risk Score 문구 추가
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.js
  src/components/charts/Histogram.module.css
  yarn.lock
Labels: Component

#493 feat(BarChart): add scroll option
  src/components/__tests__/BarChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
Labels: Component

#494 v0.13.14
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.553b81d0.js
  docs/build/bundle.553b81d0.js.LICENSE.txt
  docs/build/bundle.8cb2d5d5.js
  docs/index.html
  package.json
Labels: Build

#495 v0.13.14
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.553b81d0.js
  docs/build/bundle.553b81d0.js.LICENSE.txt
  docs/build/bundle.8cb2d5d5.js
  docs/index.html
  package.json
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/Histogram.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/charts/Histogram.js
  src/components/charts/Histogram.module.css
  yarn.lock
Labels: Build

#498 feat(RadioBox): add disabled of item
  src/components/__tests__/RadioBox.test.js
  src/components/form/RadioBox.js
Labels: Component

#497 fix: Histogram 차트의 selectbox 이벤트를 props로 받을수 있도록 합니다
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.js
  src/components/charts/Histogram.md
Labels: bug

#500 feat(PieChart): create
  src/__tests__/index.test.js
  src/components/__tests__/PieChart.test.js
  src/components/charts/PieChart.js
  src/components/charts/PieChart.md
  src/index.js
Labels: Component

#501 v0.13.15
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.553b81d0.js
  docs/build/bundle.8a109281.js
  docs/build/bundle.8a109281.js.LICENSE.txt
  docs/index.html
  package.json
Labels: Build

#502 v0.13.15
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.553b81d0.js
  docs/build/bundle.8a109281.js
  docs/build/bundle.8a109281.js.LICENSE.txt
  docs/index.html
  package.json
  src/__tests__/index.test.js
  src/components/__tests__/Histogram.test.js
  src/components/__tests__/PieChart.test.js
  src/components/__tests__/RadioBox.test.js
  src/components/charts/Histogram.js
  src/components/charts/Histogram.md
  src/components/charts/PieChart.js
  src/components/charts/PieChart.md
  src/components/form/RadioBox.js
  src/index.js
Labels: Build

#510 v0.13.16
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.20e0af21.js
  docs/build/bundle.20e0af21.js.LICENSE.txt
  docs/build/bundle.8a109281.js
  docs/index.html
  package.json
Labels: Build

#511 v0.13.16
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.20e0af21.js
  docs/build/bundle.20e0af21.js.LICENSE.txt
  docs/build/bundle.8a109281.js
  docs/index.html
  package.json
  src/components/charts/RadarChart.js
  src/components/charts/RadarChart.md
  src/components/charts/TimeToEvent.js
  src/components/charts/TimeToEvent.md
  src/components/charts/TimeToEvent.module.css
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Build
