Repository linewalks/MDwalks-UI, pull requests merged in 2020-07, with the labels that each got.

#681 feat: RadioBox가 디자인 시안과 동일하도록 수정
  src/components/form/RadioBox.js
  src/components/form/RadioBox.md
  src/components/form/RadioBox.test.js
Labels: CSS, bug

#689 improvement(eslint): eslint 미적용항목 적용
  src/assets/styles/variables.js
  src/components/TimeToEvent.test.js
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/BarChartMulti.test.js
  src/components/__tests__/SankeyChart.test.js
  src/components/__tests__/commonTag.test.js
  src/components/button/Button.js
  src/components/button/ButtonLink.test.js
  src/components/button/ButtonTextLink.test.js
  src/components/button/TextLink.test.js
  src/components/button/ToggleButton.test.js
  src/components/button/ToggleLargeButton.js
  src/components/button/ToggleLargeButton.test.js
  src/components/charts/Histogram.js
  src/components/charts/LineMergeTimeline.js
  src/components/charts/RadarChartOld.js
  src/components/charts/Timeline.js
  src/components/charts/TreeMap.js
  src/components/paper/Sequence.js
  src/components/table/Descriptions.js
  src/components/toast/Toast.js
  src/helper/DateUtility.test.js
  src/helper/chartUtility.test.js
Labels: eslint

#690 Feature/issue.685
  src/components/list/CheckList.js
  src/components/list/CheckList.test.js
Labels: Component

#692 feat(RadarChart): 레이더차트 수정
  src/components/charts/RadarChart.js
Labels: style

#695 improvement: remove colorList of PieChart
  src/components/charts/PieChart.js
Labels: Code clean

#694 feat: 타이포그래피 문서 추가
  src/assets/styles/font.md
  src/components/layout/Heading.md
Labels: StyleGuide

#701 feat(Histogram): 스타일 가이드 적용
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.js
  src/components/charts/Histogram.module.css
Labels: StyleGuide

#703 fix: PropTypes Warning 제거
  src/components/charts/TimeToEvent.js
  src/components/common/commonTag.js
Labels: bug
