Repository linewalks/MDwalks-UI, pull requests merged in 2020-06, with the labels that each got.

#632 improvement: CheckList의 일괄선택 및 해제 및 props 변화에 따른 컴포넌트 업데이트 라이프사이클 추가
  src/components/list/CheckList.js
  src/components/list/CheckList.md
  src/components/list/CheckList.test.js
Labels: Component

#637 v0.13.29
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.016459d1.js
  docs/build/bundle.0276e2a1.js
  docs/build/bundle.0276e2a1.js.LICENSE.txt
  docs/index.html
  package.json
Labels: Build

#648 fix: Button의 proptypes 오타 수정
  src/components/button/Button.js
Labels: bug

#650 improvement(LineMergeTimeline): Timeline에 Color set 적용
  src/components/charts/LineMergeTimeline.js
  src/components/charts/LineMergeTimeline.module.css
Labels: CSS, Component

#651 improvement: Table의 color 및 셀 style 변경
  src/assets/styles/tableProperties.js
  src/assets/styles/variables.js
  src/components/table/TBody.js
  src/components/table/TFoot.js
  src/components/table/THead.js
  src/components/table/Table.js
  src/components/table/Table.md
Labels: CSS, Component

#654 improvement: index에 tableProperties를 export에 추가
  src/__tests__/index.test.js
  src/index.js
Labels: Component

#660 fix: subHeader와 tbody td의 padding 불일치 문제 수정
  src/assets/styles/tableProperties.js
  src/components/table/THead.js
  src/components/table/Table.md
Labels: bug

#661 fix: border-bottom 미적용 버그 픽스
  src/components/table/Table.js
  src/components/table/Table.md
Labels: bug

#662 improvement: Description style guide 적용
  src/components/table/Descriptions.js
  src/components/table/Descriptions.md
  src/components/table/Table.md
Labels: CSS

#667 improvement: LegendList에 color를 테마로 입히는 방법 적용
  src/components/common/commonTag.js
  src/components/common/commonTag.md
Labels: CSS, Component
