Repository linewalks/MDwalks-UI, pull requests merged in 2020-08, with the labels that each got.

#708 Feature/issue.705
  src/components/list/CheckBox.js
  src/components/list/CheckBox.md
  src/components/list/CheckBox.test.js
  src/components/list/CheckList.js
  src/components/list/CheckList.md
  src/components/list/CheckList.test.js
  styleguide.config.js
Labels: Component

#710 Feature/issue.709
  src/__tests__/index.test.js
  src/components/__tests__/RadioBox.test.js
  src/components/form/RadioBox.js
  src/components/form/RadioBox.md
  src/components/form/RadioBox.test.js
  src/components/list/RadioList.js
  src/components/list/RadioList.md
  src/components/list/RadioList.test.js
  src/index.js
  styleguide.config.js
Labels: Component

#713 feat(LineMergedTimeline): circle 컬러셋 추가
  src/components/charts/LineMergeTimeline.js
Labels: StyleGuide

#717 fix(RadioList): formatter를 처리하도록 수정 및 md 케이스 추가
  src/components/list/CheckList.md
  src/components/list/RadioList.js
  src/components/list/RadioList.md
Labels: bug

#721 feat(BarChart): barSize 추가
  src/components/charts/BarChart.js
Labels: Component

#724 fix: modal이 오픈 된 후 body에 스크롤이 동작하지 않아야 합니다
  src/components/modal/Modal.js
  src/components/modal/Modal.md
Labels: bug

#729 fix(PieChart): 누락된 theme 추가
  .gitignore
  src/components/charts/PieChart.js
Labels: bug
