Repository linewalks/MDwalks-UI, pull requests merged in 2020-04, with the labels that each got.

#514 feat: Histogram 차트의 onChange event에 인자를 하나 더 추가합니다
  src/components/__tests__/Histogram.test.js
  src/components/charts/Histogram.js
  src/components/charts/Histogram.md
Labels: Component

#518 style(form): remove background of select
  src/assets/styles/form.sass
Labels: CSS, bug

#521 style(Notification): add animation
  package.json
  src/components/notifications/Notifications.js
  yarn.lock
Labels: CSS, Component

#522 fix(table): apply columns
  src/components/__tests__/Table.test.js
  src/components/table/Table.js
Labels: Component, bug

#523 v0.13.17
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.1698941c.js
  docs/build/bundle.1698941c.js.LICENSE.txt
  docs/build/bundle.20e0af21.js
  docs/index.html
  package.json
  src/components/notifications/index.js
Labels: Build

#524 v0.13.17
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.1698941c.js
  docs/build/bundle.1698941c.js.LICENSE.txt
  docs/build/bundle.20e0af21.js
  docs/index.html
  package.json
  src/__tests__/index.test.js
  src/assets/styles/form.sass
  src/components/__tests__/Histogram.test.js
  src/components/__tests__/Table.test.js
  src/components/charts/Histogram.js
  src/components/charts/Histogram.md
  src/components/notifications/Notification.js
  src/components/notifications/Notification.md
  src/components/notifications/NotificationContainer.js
  src/components/notifications/NotificationManager.js
  src/components/notifications/Notifications.js
  src/components/notifications/index.js
  src/components/table/Table.js
  src/components/toast/Toast.md
  src/index.js
  styleguide.config.js
  yarn.lock
Labels: Build

#525 docs(styleguide): add stylesheet
  src/assets/styles/spoqaHansans.css
  styleguide.config.js
Labels: bug, docs

#526 Feature/issue.505
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/LineChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/charts/LineChart.js
  src/components/charts/LineChart.md
Labels: Component

#530 feat(ColorSet): create
  src/__tests__/index.test.js
  src/components/ChartColor.js
  src/components/ChartColor.md
  src/components/ChartColor.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/charts/LineChart.js
  src/components/charts/LineChart.md
  src/components/charts/PieChart.js
  src/components/charts/PieChart.md
  src/index.js
Labels: Component

#532 feat(RadioBox): add method of unCheckedAll
  src/components/__tests__/RadioBox.test.js
  src/components/form/RadioBox.js
  src/components/form/RadioBox.md
Labels: Component

#534 v0.13.18
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.1698941c.js
  docs/build/bundle.d57e5c76.js
  docs/build/bundle.d57e5c76.js.LICENSE.txt
  docs/index.html
  package.json
Labels: Build

#536 v0.13.18
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.1698941c.js
  docs/build/bundle.d57e5c76.js
  docs/build/bundle.d57e5c76.js.LICENSE.txt
  docs/index.html
  package.json
  src/__tests__/index.test.js
  src/assets/styles/spoqaHansans.css
  src/components/ChartColor.js
  src/components/ChartColor.md
  src/components/ChartColor.test.js
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/LineChart.test.js
  src/components/__tests__/RadioBox.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/charts/LineChart.js
  src/components/charts/LineChart.md
  src/components/charts/PieChart.js
  src/components/charts/PieChart.md
  src/components/form/RadioBox.js
  src/components/form/RadioBox.md
  src/index.js
  styleguide.config.js
Labels: Build

#540 feat(BarChart): multi Theme
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/TooltipCompareContent.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/common/cdmCommon.js
  src/components/tooltip/TooltipCompareContent.js
Labels: Component

#541 v0.13.19
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.39d9c295.js
  docs/build/bundle.39d9c295.js.LICENSE.txt
  docs/build/bundle.d57e5c76.js
  docs/index.html
  package.json
Labels: Build

#545 style(SummaryCard): modify font style
  src/assets/styles/font.sass
  src/assets/svg/icn-more-modal-md-default.svg
  src/components/card/SummaryCard.js
  src/components/card/SummaryCard.md
Labels: CSS

#546 fix(RadioBox): show Icon Image
  src/components/form/RadioBox.js
Labels: Component, bug

#547 feat(WrapperScrollBars): create
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/Table.test.js
  src/components/charts/BarChart.js
  src/components/common/cdmCommon.js
  src/components/table/Table.js
Labels: CSS, Component, bug

#551 feat(BarChartMulti): create
  .eslintrc.js
  src/__tests__/index.test.js
  src/components/__tests__/BarChartMulti.test.js
  src/components/charts/BarChartMulti.js
  src/components/charts/BarChartMulti.md
  src/index.js
Labels: Component

#553 feat(index): add version
  src/__tests__/index.test.js
  src/index.js
Labels: Build

#554 v0.13.20
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.39d9c295.js
  docs/build/bundle.888e4302.js
  docs/build/bundle.888e4302.js.LICENSE.txt
  docs/index.html
  docs/static/media/icn-more-modal-md-default.078c9a91.svg
  package.json
  rollup.config.js
  yarn-error.log
  yarn.lock
Labels: Build

#555 릴리즈 v0.13.20
  .eslintrc.js
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.39d9c295.js
  docs/build/bundle.888e4302.js
  docs/build/bundle.888e4302.js.LICENSE.txt
  docs/index.html
  docs/static/media/icn-more-modal-md-default.078c9a91.svg
  package.json
  rollup.config.js
  src/__tests__/index.test.js
  src/assets/styles/font.sass
  src/assets/svg/icn-more-modal-md-default.svg
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/BarChartMulti.test.js
  src/components/__tests__/Table.test.js
  src/components/card/SummaryCard.js
  src/components/card/SummaryCard.md
  src/components/charts/BarChart.js
  src/components/charts/BarChartMulti.js
  src/components/charts/BarChartMulti.md
  src/components/common/cdmCommon.js
  src/components/form/RadioBox.js
  src/components/table/Table.js
  src/index.js
  yarn-error.log
  yarn.lock
Labels: Build

#557 improvement(BarChart): add theme
  src/components/charts/BarChart.js
Labels: bug

#558 v0.13.21
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
Labels: Build

#559 v0.13.21
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  package.json
  src/components/charts/BarChart.js
Labels: Build

#560 Feature/issue.550
  migration.md
  src/components/ChartColor.js
  src/components/ChartColor.test.js
  src/components/__tests__/BarGauge.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarGauge.js
  src/components/charts/BarGauge.module.css
  src/components/charts/Histogram.js
  src/components/charts/LineChart.js
  src/components/charts/PieChart.js
  src/components/charts/RadarChart.js
  src/components/charts/RadiusGauge.js
  src/components/charts/TimeToEvent.js
Labels: Component, style

#563 Feature/issue.562
  src/assets/svg/icn-nodata.svg
  src/assets/svg/visual-alert.svg
  src/components/__tests__/EmptyPlaceHolder.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/common/cdmCommon.js
  src/components/table/EmptyPlaceHolder.js
Labels: Component, style

#565 v0.13.22
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.434351fd.js
  docs/build/bundle.434351fd.js.LICENSE.txt
  docs/build/bundle.888e4302.js
  docs/index.html
  docs/static/media/icn-nodata.1d251f30.svg
  docs/static/media/visual-alert.bc2ffda8.svg
  package.json
Labels: Build
