Repository linewalks/MDwalks-UI, pull requests merged in 2020-09, with the labels that each got.

#740 feat: BarGauge 임계치 선 추가
  src/components/__tests__/BarGauge.test.js
  src/components/charts/BarGauge.js
  src/components/charts/BarGauge.md
Labels: Component

#745 feat: Radius Gague 임계치 선 추가
  src/assets/svg/radiusgauge/img-angulargaugechart-gaugepointer.svg
  src/assets/svg/radiusgauge/img-angulargaugechart-thresholdpointer.svg
  src/components/charts/RadiusGauge.js
  src/components/charts/RadiusGauge.md
Labels: Component

#751 improvement: Unexpected unnamed function 경고 제거
  src/components/charts/SankeyChart.js
  src/components/paper/Heatmap.js
  styleguide.config.js
Labels: Component, eslint

#755 feat(EmptyPlaceHolder): text를 받을 수 있도록 변경
  src/components/table/EmptyPlaceHolder.js
  src/components/table/TBody.js
  src/components/table/Table.js
  src/components/table/Table.md
Labels: CSS, Component
