Repository linewalks/MDwalks-UI, pull requests merged in 2020-05, with the labels that each got.

#569 feat(cartesian): create XAxis, YAxis
  src/components/charts/BarChart.js
  src/components/charts/cartesian/XAxis.js
  src/components/charts/cartesian/YAxis.js
Labels: Component

#570 style(BarChartMulti): modify color, spacing
  src/components/charts/BarChart.js
  src/components/charts/BarChartMulti.js
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Component

#573 feat: SummaryCard에서 events가 있으면 hover효과 추가, box-shadow 변경
  src/components/card/SummaryCard.js
Labels: style

#572 Feature/issue.568
  migration.md
  src/components/__tests__/BarChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/charts/cartesian/XAxis.js
Labels: Component, style

#575 Feature/version.up.v0.13.23
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.30162117.js
  docs/build/bundle.30162117.js.LICENSE.txt
  docs/build/bundle.434351fd.js
  docs/index.html
  package.json
  styleguide.config.js
Labels: Build

#577 test(SummaryCard): apply hover style when has Event
  src/components/__tests__/SummaryCard.test.js
Labels: test

#579 feat(TFoot): support colSpan
  src/components/__tests__/TFoot.test.js
  src/components/table/TFoot.js
  src/components/table/Table.md
Labels: Component

#580 feat(BarChart): support unit of XAxis, YAxis
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/LineChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/LineChart.js
Labels: Component

#593 feat(BarChart): modify barsize
  src/helper/chartUtility.js
  src/helper/chartUtility.test.js
Labels: Component, style

#596 feat: create CartesianGrid, apply XAixs to LineChart
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/LineChart.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChartMulti.js
  src/components/charts/LineChart.js
  src/components/charts/LineChart.md
  src/components/charts/cartesian/CartesianGrid.js
  src/components/charts/cartesian/XAxis.js
  src/components/charts/cartesian/YAxis.js
Labels: Component

#598 fix: set propTypes for TFoot
  src/components/table/TFoot.js
  src/components/table/Table.js
Labels: Component

#600 feat: set textMap for Charts
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/BarChartMulti.test.js
  src/components/__tests__/LineChart.test.js
  src/components/__tests__/TooltipBox.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChartMulti.js
  src/components/charts/LineChart.js
  src/components/charts/PieChart.js
  src/components/common/cdmCommon.js
  src/components/tooltip/TooltipBox.js
  src/components/tooltip/TooltipCompareContent.js
Labels: Component

#601 refactor: create utils for chart test
  package.json
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/BarChartMulti.test.js
  src/components/__tests__/LineChart.test.js
  src/components/__tests__/PieChart.test.js
  src/components/__tests__/utils.js
Labels: Component

#603 feat(ChartColor): create ThemeBubble
  src/components/ChartColor.js
  src/components/ChartColor.test.js
Labels: Component

#606 feat(RadarChart): change to rechart
  migration.md
  src/__tests__/index.test.js
  src/components/__tests__/RadarChart.test.js
  src/components/__tests__/RadarChartOld.test.js
  src/components/__tests__/utils.js
  src/components/charts/RadarChart.js
  src/components/charts/RadarChart.md
  src/components/charts/RadarChartOld.js
  src/components/charts/RadarChartOld.md
  src/components/charts/cartesian/PolarAngleAxis.js
  src/index.js
Labels: Component

#607 v0.13.26
  CHANGELOG.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.488b60ec.js
  docs/build/bundle.488b60ec.js.LICENSE.txt
  docs/build/bundle.f899b00c.js
  docs/index.html
  package.json
Labels: Build

#611 feat(Chart): use chartTitle
  src/components/__tests__/BarChart.test.js
  src/components/__tests__/RadarChart.test.js
  src/components/__tests__/utils.js
  src/components/charts/BarChart.js
  src/components/charts/BarChart.md
  src/components/charts/BarChartMulti.js
  src/components/charts/LineChart.js
  src/components/charts/PieChart.js
  src/components/charts/RadarChart.js
  src/components/common/commonTag.js
  src/components/common/commonTag.md
  src/components/table/Table.js
  src/components/tooltip/TooltipBox.js
  src/index.js
Labels: Component

#612 feat(Tabs): add type of title
  src/components/__tests__/Tabs.test.js
  src/components/layout/Tabs.js
  src/components/layout/Tabs.md
Labels: Component

#613 feat(PieChart): add layout
  src/components/charts/PieChart.js
  src/components/charts/PieChart.md
Labels: Component

#616 style: barSize, Dot margin in LegendList
  src/components/__tests__/BarChartMulti.test.js
  src/components/__tests__/commonTag.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChartMulti.js
  src/components/charts/PieChart.md
  src/components/common/commonTag.js
Labels: style

#619 feat(TimeToEvent): use Rechart
  migration.md
  src/__tests__/index.test.js
  src/components/TimeToEvent.test.js
  src/components/__tests__/TimeToEventOld.test.js
  src/components/__tests__/utils.js
  src/components/charts/TimeToEvent.js
  src/components/charts/TimeToEvent.md
  src/components/charts/TimeToEventOld.js
  src/components/charts/TimeToEventOld.md
  src/components/tooltip/TooltipBox.js
  src/index.js
Labels: Component

#621 v0.13.27
  CHANGELOG.md
  README.md
  dist/index.esm.js
  dist/index.js
  docs/build/bundle.0936223c.js
  docs/build/bundle.0936223c.js.LICENSE.txt
  docs/build/bundle.488b60ec.js
  docs/index.html
  package.json
Labels: Build

#623 feat(ChartColor): add case to ThemeComparePrimarySea
  src/components/ChartColor.js
Labels: style

#624 imporvement(ChartColor): update getColorsByTheme
  src/components/ChartColor.js
  src/components/ChartColor.test.js
Labels: style

#626 feat(LegendList): add hide option
  src/components/__tests__/commonTag.test.js
  src/components/charts/BarChart.js
  src/components/charts/BarChartMulti.js
  src/components/charts/LineChart.js
  src/components/charts/PieChart.js
  src/components/charts/RadarChart.js
  src/components/charts/TimeToEvent.js
  src/components/common/commonTag.js
Labels: Component

#625 feat(CheckList): add layout
  src/components/__tests__/Item.test.js
  src/components/list/CheckList.js
  src/components/list/CheckList.test.js
  src/components/list/Item.js
  src/components/list/RadioList.js
Labels: Component
