Repository linewalks/MDwalks-UI, pull requests merged in 2021-01, with the labels that each got.

#882 feat(Tooltip): placement 지원
  src/components/form/Tooltip.md
  src/components/form/Tooltip.test.js
  src/components/form/Tooltip.tsx
Labels: Component

#902 v0.15.0 develop release
  CHANGELOG.md
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  docs/build/bundle.afd6a3ef.js
  docs/build/bundle.afd6a3ef.js.LICENSE.txt
  docs/build/bundle.c37ab5bc.js
  docs/index.html
  docs/static/media/btn_checkbox_checked_16.834b7960.svg
  docs/static/media/btn_checkbox_checked_24.0e4b748b.svg
  docs/static/media/btn_checkbox_checked_disabled_16.7122c3b3.svg
  docs/static/media/btn_checkbox_checked_disabled_24.04a540cb.svg
  docs/static/media/btn_checkbox_unchecked_16.7808a8f6.svg
  docs/static/media/btn_checkbox_unchecked_24.1a0367c2.svg
  docs/static/media/btn_checkbox_unchecked_disabled_16.ac3f9781.svg
  docs/static/media/btn_checkbox_unchecked_disabled_24.ec7b0dd5.svg
  docs/static/media/btn_pagination_next_32.17867819.svg
  docs/static/media/btn_pagination_next_42.d5e875a9.svg
  docs/static/media/btn_pagination_previous_32.07db1a58.svg
  docs/static/media/btn_pagination_previous_42.48bcb21e.svg
  docs/static/media/btn_radiobutton_checked_24.da92559a.svg
  docs/static/media/btn_radiobutton_checked_disabled_24.2e20b40e.svg
  docs/static/media/btn_radiobutton_unchecked_24.cf54b8d8.svg
  docs/static/media/btn_radiobutton_unchecked_disabled_24.e1b70c00.svg
  docs/static/media/icn_arrow_upright_24.87648dca.svg
  docs/static/media/icn_chevron_down_16.9546b385.svg
  docs/static/media/icn_chevron_down_24.0db1fa2f.svg
  docs/static/media/icn_chevron_filled_right_16.24470d4c.svg
  docs/static/media/icn_close_32.320d537c.svg
  docs/static/media/icn_close_pmblue_16.7e4ac7c5.svg
  docs/static/media/icn_close_red01_16.4819f22b.svg
  docs/static/media/icn_done_circle_filled_pmblue_24.bf4f7063.svg
  docs/static/media/icn_error_circle_filled_red01_24.ccb536fe.svg
  docs/static/media/icn_sort_down_filled_disabled_grey06_16.8171ca1e.svg
  docs/static/media/icn_sort_down_filled_selected_grey09_16.9859f322.svg
  docs/static/media/icn_sort_down_filled_unselected_grey07_16.4b1aeecc.svg
  docs/static/media/icn_sort_up_filled_disabled_grey06_16.86e30d03.svg
  docs/static/media/icn_sort_up_filled_selected_grey09_16.af41faca.svg
  docs/static/media/icn_sort_up_filled_unselected_grey07_16.871208db.svg
  docs/static/media/picto_nodata.163e6fd3.svg
  package.json
Labels: Build

#905 feat: add component_requirement template
  COMPONENT_REQUIREMENT.md
Labels: docs

#907 feat: docusaurus 추가 및 컴포넌트 정의서 템플릿 수정
  .babelrc
  .gitignore
  README.md
  docus/basic/CR_template.md
  docus/basic/introduction.md
  docus/button/Button.md
  docus/button/ButtonLink.md
  docusaurus.config.js
  package.json
  src/pages/custom.css
  src/pages/index.js
  src/pages/sidebars.js
  src/pages/styles.module.css
  static/img/favicon.ico
  static/img/logo.svg
  yarn.lock
Labels: docs
