Repository linewalks/MDwalks-UI, pull requests merged in 2021-02, with the labels that each got.

#910 Feature/issue.908
  docus/list/CheckBox.md
  docus/list/CheckList.md
  docus/list/Item.md
  docus/list/RadioList.md
  src/components/list/CheckBox.tsx
  src/components/list/CheckList.tsx
  src/components/list/Item.tsx
  src/components/list/RadioList.tsx
  src/pages/sidebars.js
Labels: docs

#913 docs: add Status Images of travis
  README.md
Labels: docs

#918 fix(Pagination): radius 적용
  src/components/pagination/Pagination.tsx
Labels: bug

#914 Feature/issue.912
  .babelrc
  .travis.yml
  dist/index.esm.js
  dist/index.esm.js.map
  dist/index.js
  dist/index.js.map
  package.json
  rollup.config.js
  src/__tests__/index.test.js
  src/assets/styles/variables.sass
  src/components/progressbar/ProgressBar.md
  src/components/progressbar/ProgressBar.sass
  src/components/progressbar/ProgressBar.test.js
  src/components/progressbar/ProgressBar.tsx
  src/index.ts
  styleguide.config.js
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: Component

#919 improvement: ProgressBar sass 파일 yarn version 시 임포트 문제 수정
  src/components/progressbar/ProgressBar.sass
Labels: Build

#923 improvement: modify changelog
  CHANGELOG.md
Labels: Build, CI

#926 fix(ProgressBar): border-radius 수정
  src/components/progressbar/ProgressBar.sass
  src/components/progressbar/ProgressBar.tsx
Labels: bug

#927 Feature/issue.911
  docus/layout/Footer.md
  docus/layout/Heading.md
  docus/layout/Image.md
  docus/layout/Navbar.md
  docus/layout/Tabs.md
  src/components/layout/Footer.md
  src/components/layout/Footer.tsx
  src/components/layout/Image.md
  src/components/layout/Image.tsx
  src/components/layout/Navbar.md
  src/components/layout/Navbar.tsx
  src/components/layout/Tabs.tsx
  src/pages/sidebars.js
  styleguide.config.js
Labels: docs

#917 feat: [Docs] charts
  docus/charts/BarChart.md
  docus/charts/BarChartMulti.md
  docus/charts/BarGauge.md
  docus/charts/Histogram.md
  docus/charts/LineChart.md
  docus/charts/LineMergeTimeline.md
  docus/charts/PieChart.md
  docus/charts/RadarChart.md
  docus/charts/RadiusGauge.md
  docus/charts/SankeyChart.md
  docus/charts/TimeToEvent.md
  docus/charts/Timeline.md
  docus/charts/TreeMap.md
  docus/charts/cartesian/CartesianGrid.md
  docus/charts/cartesian/XAxis.md
  docus/charts/cartesian/YAxis.md
  package.json
  src/pages/sidebars.js
  static/img/histogram.png
  static/img/linemergetimeline.png
  static/img/radiusgauge.png
  static/img/sankey.png
  static/img/timeline.png
  webpack.config.js
Labels: docs
